apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-openiiot.yml -o ./k8s_yaml_files
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: openiiot-emqx1
  name: openiiot-emqx1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openiiot-emqx1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-openiiot.yml -o ./k8s_yaml_files
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/tools-default: "true"
        io.kompose.service: openiiot-emqx1
    spec:
      containers:
        - env:
            - name: EMQX_CLUSTER__DISCOVERY_STRATEGY
              value: static
            - name: EMQX_CLUSTER__STATIC__SEEDS
              value: '[emqx@node1.emqx.io,emqx@node2.emqx.io]'
            - name: EMQX_NODE_NAME
              value: emqx@node1.emqx.io
          image: openiiot_emqx:1.0.0
          livenessProbe:
            exec:
              command:
                - /opt/emqx/bin/emqx
                - ctl
                - status
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 25
          name: openiiot-emqx1
          ports:
            - containerPort: 1883
              hostPort: 1883
              protocol: TCP
            - containerPort: 8083
              hostPort: 8083
              protocol: TCP
            - containerPort: 8084
              hostPort: 8084
              protocol: TCP
            - containerPort: 8883
              hostPort: 8883
              protocol: TCP
            - containerPort: 18083
              hostPort: 18083
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /opt/emqx/data
              name: emqx1-data
      restartPolicy: Always
      volumes:
        - name: emqx1-data
          persistentVolumeClaim:
            claimName: emqx1-data
status: {}
