apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-openiiot.yml -o ./k8s_yaml_files
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: openiiot-tdengine
  name: openiiot-tdengine
spec:
  ports:
    - name: "6030"
      port: 6030
      targetPort: 6030
    - name: "6041"
      port: 6041
      targetPort: 6041
    - name: "6043"
      port: 6043
      targetPort: 6043
    - name: "6044"
      port: 6044
      targetPort: 6044
    - name: "6045"
      port: 6045
      targetPort: 6045
    - name: "6046"
      port: 6046
      targetPort: 6046
    - name: "6047"
      port: 6047
      targetPort: 6047
    - name: "6048"
      port: 6048
      targetPort: 6048
    - name: "6049"
      port: 6049
      targetPort: 6049
    - name: 6043-udp
      port: 6043
      protocol: UDP
      targetPort: 6043
    - name: 6044-udp
      port: 6044
      protocol: UDP
      targetPort: 6044
    - name: 6045-udp
      port: 6045
      protocol: UDP
      targetPort: 6045
    - name: 6046-udp
      port: 6046
      protocol: UDP
      targetPort: 6046
    - name: 6047-udp
      port: 6047
      protocol: UDP
      targetPort: 6047
    - name: 6048-udp
      port: 6048
      protocol: UDP
      targetPort: 6048
    - name: 6049-udp
      port: 6049
      protocol: UDP
      targetPort: 6049
  selector:
    io.kompose.service: openiiot-tdengine
status:
  loadBalancer: {}
