apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-openiiot.yml -o ./k8s_yaml_files
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: openiiot-grafana
  name: openiiot-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openiiot-grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-openiiot.yml -o ./k8s_yaml_files
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/tools-default: "true"
        io.kompose.service: openiiot-grafana
    spec:
      containers:
        - image: openiiot_grafana:1.0.0
          name: openiiot-grafana
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-data
      restartPolicy: Always
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data
status: {}
