version: '3'
services:
  node-red:
    build:
      context: .
      dockerfile: Dockerfile
    image: eco-registry.supos.com/supvxcen/node-red:1.0.1
    platform: linux/amd64
    ports:
      - "1880:1880"
    volumes:
      - nodered:/data
    environment:
      - TZ=UTC
    restart: always
volumes:
  nodered:
