Develop:
  ServicePort: "6789"
  DebugPort: "6790"
  EnablePprof: true
  LogLevel: "debug"
  LogInterval: "hour"
  EnableMetrics: false
  ConsoleLog: true
  AgentLog: true
  FileLog: true

Product:
  ServicePort: "6789"
  DebugPort: "6790"
  EnablePprof: true
  LogLevel: "info"
  LogInterval: "hour"
  EnableMetrics: true
  ConsoleLog: false
  AgentLog: true
  FileLog: true
