apiVersion: batch/v1
kind: Job
metadata:
  name: install-grafana-plugins
  namespace: openiiot
spec:
  ttlSecondsAfterFinished: 100  # This delay allows you to check the job's logs or status even after completion
  template:
    spec:
      containers:
      - name: install-plugins
        image: localhost:5000/openiiot_grafana:1.0.0
        command: ["/bin/sh", "-c", "/opt/grafana/install-plugins.sh"]
        volumeMounts:
        - name: plugin-volume
          mountPath: /var/lib/grafana
      restartPolicy: Never
      volumes:
      - name: plugin-volume
        persistentVolumeClaim:
          claimName: openiiot-grafana-pvc
