apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openiiot-grafana-pvc
  namespace: openiiot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
      matchLabels:
        type: openiiot-grafana
