apiVersion: v1
kind: PersistentVolume
metadata:
  name: openiiot-tdengine-log-pv
  labels:
    type: openiiot-tdengine-log
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 127.0.0.1
    path: "/volumes/nfs/openiiot/tdengine_log"

