apiVersion: v1
kind: Service
metadata:
  name: openiiot-emqx-service
  namespace: openiiot
spec:
  type: NodePort
  ports:
    - name: emqx1883
      port: 1883
      targetPort: 1883
      nodePort: 30883
    - name: emqx8083
      port: 8083
      targetPort: 8083
      nodePort: 30083
    - name: emqx8084
      port: 8084
      targetPort: 8084
      nodePort: 30084
    - name: emqx8883
      port: 8883
      targetPort: 8883
      nodePort: 31883
    - name: emqx18883
      port: 18083
      targetPort: 18083
      nodePort: 31083
  selector:
    app: openiiot-emqx

