apiVersion: v1
kind: PersistentVolume
metadata:
  name: openiiot-nodered-pv
  labels:
    type: openiiot-nodered
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 127.0.0.1
    path: "/volumes/nfs/openiiot/nodered_data"

