apiVersion: v1
kind: Service
metadata:
  name: openiiot-nodered-service
  namespace: openiiot
spec:
  type: NodePort
  ports:
    - name: nodered1880
      port: 1880
      targetPort: 1880
      nodePort: 31880
    - name: nodered43893
      port: 43893
      targetPort: 43893
      nodePort: 31893
  selector:
    app: openiiot-nodered

