apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openiiot-tdengine-log-pvc
  namespace: openiiot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: openiiot-tdengine-log
