{
 "title": "Test dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select * from demo.air_quality_1;"
    }
   ]
  },
  {
   "title": "Total running time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select sum(time_duration) as Pause_time from (select first(ts) as start_time, spread(ts) as time_duration, status from demo.air_quality_1 state_window(status)) where status = \"pause\" group by status;"
    },
    {
     "formatType": "Time series",
     "sql": "select sum(time_duration) as Unknown_stop_time from (select first(ts) as start_time, spread(ts) as time_duration, status from demo.air_quality_1 state_window(status)) where status = \"unknown stop\" group by status;"
    },
    {
     "formatType": "Time series",
     "sql": "select sum(time_duration) as Momentary_stop_time from (select first(ts) as start_time, spread(ts) as time_duration, status from demo.air_quality_1 state_window(status)) where status = \"momentary stop\" group by status;",
     "timeShiftUnit": "seconds"
    },
    {
     "formatType": "Time series",
     "sql": "select sum(time_duration) as Not_available_time from (select first(ts) as start_time, spread(ts) as time_duration, status from demo.air_quality_1 state_window(status)) where status = \"not available\" group by status;"
    },
    {
     "formatType": "Time series",
     "sql": "select sum(time_duration) as Preparation_time from (select first(ts) as start_time, spread(ts) as time_duration, status from demo.air_quality_1 state_window(status)) where status = \"preparation\" group by status;"
    },
    {
     "formatType": "Time series",
     "sql": "select sum(time_duration) as Maintenance_time from (select first(ts) as start_time, spread(ts) as time_duration, status from demo.air_quality_1 state_window(status)) where status = \"maintenance\" group by status;"
    },
    {
     "formatType": "Time series",
     "sql": "select sum(time_duration) as Post_processing_time from (select first(ts) as start_time, spread(ts) as time_duration, status from demo.air_quality_1 state_window(status)) where status = \"post-processing\" group by status;"
    },
    {
     "formatType": "Time series",
     "sql": "select sum(time_duration) as Other_technical_malfunction_time from (select first(ts) as start_time, spread(ts) as time_duration, status from demo.air_quality_1 state_window(status)) where status = \"other technical malfunction\" group by status;"
    },
    {
     "formatType": "Time series",
     "sql": "select sum(time_duration) /1000 as Running_time from (select first(ts) as start_time, spread(ts) as time_duration, status from demo.air_quality_1 state_window(status)) where status = \"running\" group by status;"
    }
   ]
  },
  {
   "title": "Current status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last_row(ts, status) from demo.air_quality_1;"
    }
   ]
  },
  {
   "title": "Contribution",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 7 },
   "targets": [
    {},
    {},
    {},
    {}
   ]
  },
  {
   "title": "Machine status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select ts, status from demo.air_quality_1;"
    }
   ]
  },
  {
   "title": "Status list",
   "type": "table",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select ts, status from demo.air_quality_1 limit 100;"
    }
   ]
  },
  {
   "title": "Number of devices",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "test/draeger" }
   ]
  },
  {
   "title": "Number of entries",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  { "title": "Dog", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 3, "x": 15, "y": 17 } },
  { "title": "motor", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 3, "x": 18, "y": 17 } },
  { "title": "Device", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 3, "x": 21, "y": 17 } },
  { "type": "cloudspout-button-panel", "gridPos": { "h": 2, "w": 3, "x": 15, "y": 20 } },
  { "type": "cloudspout-button-panel", "gridPos": { "h": 2, "w": 3, "x": 18, "y": 20 } },
  { "type": "cloudspout-button-panel", "gridPos": { "h": 2, "w": 3, "x": 21, "y": 20 } },
  { "type": "cloudspout-button-panel", "gridPos": { "h": 2, "w": 3, "x": 15, "y": 22 } },
  { "type": "cloudspout-button-panel", "gridPos": { "h": 2, "w": 3, "x": 18, "y": 22 } },
  { "type": "cloudspout-button-panel", "gridPos": { "h": 2, "w": 3, "x": 21, "y": 22 } },
  {
   "title": "Device",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 23 },
   "targets": [
    {
     "topic": "openiiot/air_quality/DDATA/Riyadh/node7/restful"
    }
   ]
  },
  {
   "title": "NFC",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 23 },
   "targets": [
    {}
   ]
  },
  { "type": "cloudspout-button-panel", "gridPos": { "h": 2, "w": 3, "x": 15, "y": 24 } },
  { "type": "cloudspout-button-panel", "gridPos": { "h": 2, "w": 3, "x": 18, "y": 24 } },
  { "type": "cloudspout-button-panel", "gridPos": { "h": 2, "w": 3, "x": 21, "y": 24 } },
  { "title": "Alert", "type": "alertlist", "gridPos": { "h": 4, "w": 9, "x": 15, "y": 26 } }
 ]
}