apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openiiot-server-pvc
  namespace: openiiot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
      matchLabels:
        type: openiiot-server