apiVersion: v1
kind: Service
metadata:
  name: openiiot-nodered-service-13
  namespace: openiiot-nodered
spec:
  type: NodePort
  ports:
    - name: nodered1880
      port: 1880
      targetPort: 1880
      nodePort: 30063
  selector:
    app: openiiot-nodered-13

