apiVersion: batch/v1
kind: Job
metadata:
  name: install-nodered-plugins
  namespace: openiiot
spec:
  ttlSecondsAfterFinished: 100  # This delay allows you to check the job's logs or status even after completion
  template:
    spec:
      containers:
      - name: install-plugins
        image: openiiot_nodered:1.0.0
        command: ["/bin/sh", "-c"]
        args: ["cp /opt/nodered/package.json /data/ && /opt/nodered/install-plugins.sh"]
        volumeMounts:
        - name: plugin-volume
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: plugin-volume
        persistentVolumeClaim:
          claimName: openiiot-nodered-pvc
