apiVersion: apps/v1
kind: Deployment
metadata:
  name: openiiot-grafana
  namespace: openiiot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openiiot-grafana
  template:
    metadata:
      labels:
        app: openiiot-grafana
    spec:
      containers:
        - name: openiiot-grafana
          image: openiiot_grafana:1.0.0
          env:
          - name: GF_SECURITY_ALLOW_EMBEDDING
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_NAME
            value: "Main Org."
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: "Admin"
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"

