apiVersion: v1
kind: PersistentVolume
metadata:
  name: openiiot-mysql-pv
  labels:
    type: openiiot-mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.186
    path: "/volumes/nfs/openiiot/mysql_data"

