apiVersion: apps/v1
kind: Deployment
metadata:
  name: openiiot-mysql
  namespace: openiiot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openiiot-mysql
  template:
    metadata:
      labels:
        app: openiiot-mysql
    spec:
      containers:
        - name: openiiot-mysql
          image: openiiot_mysql:1.0.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root1234"
            - name: MYSQL_DATABASE
              value: "openiiot"
            - name: MYSQL_USER
              value: "openiiot"
            - name: MYSQL_PASSWORD
              value: "root1234"
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"

