apiVersion: v1
kind: PersistentVolume
metadata:
  name: openiiot-emqx-pv
  labels:
    type: openiiot-emqx
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.186
    path: "/volumes/nfs/openiiot/emqx_data"

