apiVersion: v1
kind: Service
metadata:
  name: openiiot-consolemanager-service
  namespace: openiiot
spec:
  type: NodePort
  ports:
    - name: consolemanager81
      port: 81
      targetPort: 81
      nodePort: 30081
  selector:
    app: openiiot-consolemanager

