apiVersion: v1
kind: Secret
metadata:
  name: admin-user-manual-token
  annotations:
    kubernetes.io/service-account.name: admin-user
  namespace: kube-system
type: kubernetes.io/service-account-token
