// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.25.1
// source: freezonex/openiiot_api/emqx.proto

package freezonex_openiiot_api

import (
	_ "freezonex/openiiot/biz/model/api"
	base_req "freezonex/openiiot/biz/model/base_req"
	base_resp "freezonex/openiiot/biz/model/base_resp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmqxDSN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host     string `protobuf:"bytes,1,opt,name=host,proto3" json:"host" form:"host" query:"host"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username" form:"username" query:"username"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password" form:"password" query:"password"`
}

func (x *EmqxDSN) Reset() {
	*x = EmqxDSN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freezonex_openiiot_api_emqx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmqxDSN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmqxDSN) ProtoMessage() {}

func (x *EmqxDSN) ProtoReflect() protoreflect.Message {
	mi := &file_freezonex_openiiot_api_emqx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmqxDSN.ProtoReflect.Descriptor instead.
func (*EmqxDSN) Descriptor() ([]byte, []int) {
	return file_freezonex_openiiot_api_emqx_proto_rawDescGZIP(), []int{0}
}

func (x *EmqxDSN) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *EmqxDSN) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *EmqxDSN) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type EmqxStatusStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RelVsn       string `protobuf:"bytes,1,opt,name=rel_vsn,json=relVsn,proto3" json:"rel_vsn" form:"rel_vsn" query:"rel_vsn"`
	NodeName     string `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name" form:"node_name" query:"node_name"`
	BrokerStatus string `protobuf:"bytes,3,opt,name=broker_status,json=brokerStatus,proto3" json:"broker_status" form:"broker_status" query:"broker_status"`
	AppStatus    string `protobuf:"bytes,4,opt,name=app_status,json=appStatus,proto3" json:"app_status" form:"app_status" query:"app_status"`
}

func (x *EmqxStatusStruct) Reset() {
	*x = EmqxStatusStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freezonex_openiiot_api_emqx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmqxStatusStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmqxStatusStruct) ProtoMessage() {}

func (x *EmqxStatusStruct) ProtoReflect() protoreflect.Message {
	mi := &file_freezonex_openiiot_api_emqx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmqxStatusStruct.ProtoReflect.Descriptor instead.
func (*EmqxStatusStruct) Descriptor() ([]byte, []int) {
	return file_freezonex_openiiot_api_emqx_proto_rawDescGZIP(), []int{1}
}

func (x *EmqxStatusStruct) GetRelVsn() string {
	if x != nil {
		return x.RelVsn
	}
	return ""
}

func (x *EmqxStatusStruct) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *EmqxStatusStruct) GetBrokerStatus() string {
	if x != nil {
		return x.BrokerStatus
	}
	return ""
}

func (x *EmqxStatusStruct) GetAppStatus() string {
	if x != nil {
		return x.AppStatus
	}
	return ""
}

type EmqxGetStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest *base_req.BaseRequest `protobuf:"bytes,1,opt,name=base_request,json=baseRequest,proto3" json:"base_request" form:"base_request" query:"base_request"`
	Dsn         *EmqxDSN              `protobuf:"bytes,2,opt,name=dsn,proto3" json:"dsn" form:"dsn" query:"dsn"`
}

func (x *EmqxGetStatusRequest) Reset() {
	*x = EmqxGetStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freezonex_openiiot_api_emqx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmqxGetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmqxGetStatusRequest) ProtoMessage() {}

func (x *EmqxGetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freezonex_openiiot_api_emqx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmqxGetStatusRequest.ProtoReflect.Descriptor instead.
func (*EmqxGetStatusRequest) Descriptor() ([]byte, []int) {
	return file_freezonex_openiiot_api_emqx_proto_rawDescGZIP(), []int{2}
}

func (x *EmqxGetStatusRequest) GetBaseRequest() *base_req.BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *EmqxGetStatusRequest) GetDsn() *EmqxDSN {
	if x != nil {
		return x.Dsn
	}
	return nil
}

type EmqxGetStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResp *base_resp.BaseResponse `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp" form:"base_resp" query:"base_resp"`
	Status   *EmqxStatusStruct       `protobuf:"bytes,2,opt,name=status,proto3" json:"status" form:"status" query:"status"`
}

func (x *EmqxGetStatusResponse) Reset() {
	*x = EmqxGetStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freezonex_openiiot_api_emqx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmqxGetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmqxGetStatusResponse) ProtoMessage() {}

func (x *EmqxGetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freezonex_openiiot_api_emqx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmqxGetStatusResponse.ProtoReflect.Descriptor instead.
func (*EmqxGetStatusResponse) Descriptor() ([]byte, []int) {
	return file_freezonex_openiiot_api_emqx_proto_rawDescGZIP(), []int{3}
}

func (x *EmqxGetStatusResponse) GetBaseResp() *base_resp.BaseResponse {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *EmqxGetStatusResponse) GetStatus() *EmqxStatusStruct {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_freezonex_openiiot_api_emqx_proto protoreflect.FileDescriptor

var file_freezonex_openiiot_api_emqx_proto_rawDesc = []byte{
	0x0a, 0x21, 0x66, 0x72, 0x65, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x78, 0x2f, 0x6f, 0x70, 0x65, 0x6e,
	0x69, 0x69, 0x6f, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x6d, 0x71, 0x78, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x16, 0x66, 0x72, 0x65, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x78, 0x2e, 0x6f,
	0x70, 0x65, 0x6e, 0x69, 0x69, 0x6f, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x1a, 0x66, 0x72, 0x65,
	0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x78, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x66, 0x72, 0x65, 0x65, 0x7a, 0x6f, 0x6e,
	0x65, 0x78, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x66, 0x72, 0x65, 0x65, 0x7a,
	0x6f, 0x6e, 0x65, 0x78, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x62, 0x61, 0x73, 0x65,
	0x5f, 0x72, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x07, 0x45, 0x6d,
	0x71, 0x78, 0x44, 0x53, 0x4e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x22, 0x8c, 0x01, 0x0a, 0x10, 0x45, 0x6d, 0x71, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x65, 0x6c, 0x5f, 0x76, 0x73,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6c, 0x56, 0x73, 0x6e, 0x12,
	0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x70, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x83, 0x01, 0x0a, 0x14, 0x45, 0x6d, 0x71, 0x78, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0c, 0x62, 0x61, 0x73,
	0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x03, 0x64, 0x73, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x66, 0x72, 0x65, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x78, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x69, 0x69, 0x6f, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6d, 0x71, 0x78, 0x44, 0x53,
	0x4e, 0x52, 0x03, 0x64, 0x73, 0x6e, 0x22, 0x8f, 0x01, 0x0a, 0x15, 0x45, 0x6d, 0x71, 0x78, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x34, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x2e,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x62, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x40, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x66, 0x72, 0x65, 0x65, 0x7a, 0x6f, 0x6e,
	0x65, 0x78, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x69, 0x6f, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x45, 0x6d, 0x71, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x35, 0x5a, 0x33, 0x66, 0x72, 0x65, 0x65,
	0x7a, 0x6f, 0x6e, 0x65, 0x78, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x69, 0x6f, 0x74, 0x2f, 0x62,
	0x69, 0x7a, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x66, 0x72, 0x65, 0x65, 0x7a, 0x6f, 0x6e,
	0x65, 0x78, 0x5f, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x69, 0x6f, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_freezonex_openiiot_api_emqx_proto_rawDescOnce sync.Once
	file_freezonex_openiiot_api_emqx_proto_rawDescData = file_freezonex_openiiot_api_emqx_proto_rawDesc
)

func file_freezonex_openiiot_api_emqx_proto_rawDescGZIP() []byte {
	file_freezonex_openiiot_api_emqx_proto_rawDescOnce.Do(func() {
		file_freezonex_openiiot_api_emqx_proto_rawDescData = protoimpl.X.CompressGZIP(file_freezonex_openiiot_api_emqx_proto_rawDescData)
	})
	return file_freezonex_openiiot_api_emqx_proto_rawDescData
}

var file_freezonex_openiiot_api_emqx_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_freezonex_openiiot_api_emqx_proto_goTypes = []interface{}{
	(*EmqxDSN)(nil),                // 0: freezonex.openiiot_api.EmqxDSN
	(*EmqxStatusStruct)(nil),       // 1: freezonex.openiiot_api.EmqxStatusStruct
	(*EmqxGetStatusRequest)(nil),   // 2: freezonex.openiiot_api.EmqxGetStatusRequest
	(*EmqxGetStatusResponse)(nil),  // 3: freezonex.openiiot_api.EmqxGetStatusResponse
	(*base_req.BaseRequest)(nil),   // 4: base_req.BaseRequest
	(*base_resp.BaseResponse)(nil), // 5: base_resp.BaseResponse
}
var file_freezonex_openiiot_api_emqx_proto_depIdxs = []int32{
	4, // 0: freezonex.openiiot_api.EmqxGetStatusRequest.base_request:type_name -> base_req.BaseRequest
	0, // 1: freezonex.openiiot_api.EmqxGetStatusRequest.dsn:type_name -> freezonex.openiiot_api.EmqxDSN
	5, // 2: freezonex.openiiot_api.EmqxGetStatusResponse.base_resp:type_name -> base_resp.BaseResponse
	1, // 3: freezonex.openiiot_api.EmqxGetStatusResponse.status:type_name -> freezonex.openiiot_api.EmqxStatusStruct
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_freezonex_openiiot_api_emqx_proto_init() }
func file_freezonex_openiiot_api_emqx_proto_init() {
	if File_freezonex_openiiot_api_emqx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_freezonex_openiiot_api_emqx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmqxDSN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freezonex_openiiot_api_emqx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmqxStatusStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freezonex_openiiot_api_emqx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmqxGetStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freezonex_openiiot_api_emqx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmqxGetStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_freezonex_openiiot_api_emqx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_freezonex_openiiot_api_emqx_proto_goTypes,
		DependencyIndexes: file_freezonex_openiiot_api_emqx_proto_depIdxs,
		MessageInfos:      file_freezonex_openiiot_api_emqx_proto_msgTypes,
	}.Build()
	File_freezonex_openiiot_api_emqx_proto = out.File
	file_freezonex_openiiot_api_emqx_proto_rawDesc = nil
	file_freezonex_openiiot_api_emqx_proto_goTypes = nil
	file_freezonex_openiiot_api_emqx_proto_depIdxs = nil
}
