// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.24.4
// source: freezonex/openiiot_api/grafana.proto

package freezonex_openiiot_api

import (
	_ "freezonex/openiiot/biz/model/api"
	_ "freezonex/openiiot/biz/model/base_req"
	base_resp "freezonex/openiiot/biz/model/base_resp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrafanaAuthorizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RedirectUri string `protobuf:"bytes,1,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri" query:"redirect_uri"`
	State       string `protobuf:"bytes,2,opt,name=state,proto3" json:"state" query:"state"`
}

func (x *GrafanaAuthorizeRequest) Reset() {
	*x = GrafanaAuthorizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freezonex_openiiot_api_grafana_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrafanaAuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaAuthorizeRequest) ProtoMessage() {}

func (x *GrafanaAuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freezonex_openiiot_api_grafana_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaAuthorizeRequest.ProtoReflect.Descriptor instead.
func (*GrafanaAuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_freezonex_openiiot_api_grafana_proto_rawDescGZIP(), []int{0}
}

func (x *GrafanaAuthorizeRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *GrafanaAuthorizeRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type GrafanaAuthorizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResp *base_resp.BaseResponse `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp" form:"base_resp" query:"base_resp"`
}

func (x *GrafanaAuthorizeResponse) Reset() {
	*x = GrafanaAuthorizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freezonex_openiiot_api_grafana_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrafanaAuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaAuthorizeResponse) ProtoMessage() {}

func (x *GrafanaAuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freezonex_openiiot_api_grafana_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaAuthorizeResponse.ProtoReflect.Descriptor instead.
func (*GrafanaAuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_freezonex_openiiot_api_grafana_proto_rawDescGZIP(), []int{1}
}

func (x *GrafanaAuthorizeResponse) GetBaseResp() *base_resp.BaseResponse {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type GrafanaAccessTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        string `protobuf:"bytes,1,opt,name=code,proto3" json:"code" form:"code" query:"code"`
	GrantType   string `protobuf:"bytes,2,opt,name=grant_type,json=grantType,proto3" json:"grant_type" form:"grant_type" query:"grant_type"`
	RedirectUri string `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri" form:"redirect_uri" query:"redirect_uri"`
}

func (x *GrafanaAccessTokenRequest) Reset() {
	*x = GrafanaAccessTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freezonex_openiiot_api_grafana_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrafanaAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaAccessTokenRequest) ProtoMessage() {}

func (x *GrafanaAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freezonex_openiiot_api_grafana_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*GrafanaAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_freezonex_openiiot_api_grafana_proto_rawDescGZIP(), []int{2}
}

func (x *GrafanaAccessTokenRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GrafanaAccessTokenRequest) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *GrafanaAccessTokenRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type GrafanaAccessTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResp     *base_resp.BaseResponse `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp" form:"base_resp" query:"base_resp"`
	AccessToken  string                  `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token" form:"access_token" query:"access_token"`
	TokenType    string                  `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type" form:"token_type" query:"token_type"`
	ExpiresIn    int32                   `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in" form:"expires_in" query:"expires_in"`
	RefreshToken string                  `protobuf:"bytes,5,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token" form:"refresh_token" query:"refresh_token"`
}

func (x *GrafanaAccessTokenResponse) Reset() {
	*x = GrafanaAccessTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freezonex_openiiot_api_grafana_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrafanaAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaAccessTokenResponse) ProtoMessage() {}

func (x *GrafanaAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freezonex_openiiot_api_grafana_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*GrafanaAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_freezonex_openiiot_api_grafana_proto_rawDescGZIP(), []int{3}
}

func (x *GrafanaAccessTokenResponse) GetBaseResp() *base_resp.BaseResponse {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *GrafanaAccessTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GrafanaAccessTokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *GrafanaAccessTokenResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *GrafanaAccessTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type GrafanaUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorization string `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization" header:"Authorization"`
}

func (x *GrafanaUserRequest) Reset() {
	*x = GrafanaUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freezonex_openiiot_api_grafana_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrafanaUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaUserRequest) ProtoMessage() {}

func (x *GrafanaUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freezonex_openiiot_api_grafana_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaUserRequest.ProtoReflect.Descriptor instead.
func (*GrafanaUserRequest) Descriptor() ([]byte, []int) {
	return file_freezonex_openiiot_api_grafana_proto_rawDescGZIP(), []int{4}
}

func (x *GrafanaUserRequest) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

type GrafanaUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResp *base_resp.BaseResponse `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp" form:"base_resp" query:"base_resp"`
	Sub      string                  `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub" form:"sub" query:"sub"`
	Email    string                  `protobuf:"bytes,3,opt,name=email,proto3" json:"email" form:"email" query:"email"`
	Name     string                  `protobuf:"bytes,4,opt,name=name,proto3" json:"name" form:"name" query:"name"`
	Role     []string                `protobuf:"bytes,5,rep,name=role,proto3" json:"role" form:"role" query:"role"`
}

func (x *GrafanaUserResponse) Reset() {
	*x = GrafanaUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freezonex_openiiot_api_grafana_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrafanaUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaUserResponse) ProtoMessage() {}

func (x *GrafanaUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freezonex_openiiot_api_grafana_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaUserResponse.ProtoReflect.Descriptor instead.
func (*GrafanaUserResponse) Descriptor() ([]byte, []int) {
	return file_freezonex_openiiot_api_grafana_proto_rawDescGZIP(), []int{5}
}

func (x *GrafanaUserResponse) GetBaseResp() *base_resp.BaseResponse {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *GrafanaUserResponse) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *GrafanaUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GrafanaUserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrafanaUserResponse) GetRole() []string {
	if x != nil {
		return x.Role
	}
	return nil
}

var File_freezonex_openiiot_api_grafana_proto protoreflect.FileDescriptor

var file_freezonex_openiiot_api_grafana_proto_rawDesc = []byte{
	0x0a, 0x24, 0x66, 0x72, 0x65, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x78, 0x2f, 0x6f, 0x70, 0x65, 0x6e,
	0x69, 0x69, 0x6f, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x61, 0x66, 0x61, 0x6e, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x66, 0x72, 0x65, 0x65, 0x7a, 0x6f, 0x6e, 0x65,
	0x78, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x69, 0x6f, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x1a,
	0x66, 0x72, 0x65, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x78, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x66, 0x72, 0x65, 0x65,
	0x7a, 0x6f, 0x6e, 0x65, 0x78, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x62, 0x61, 0x73,
	0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x66, 0x72,
	0x65, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x78, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x62,
	0x61, 0x73, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a,
	0x17, 0x47, 0x72, 0x61, 0x66, 0x61, 0x6e, 0x61, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x0c, 0x72, 0x65, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x10,
	0xb2, 0xbb, 0x18, 0x0c, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x75, 0x72, 0x69,
	0x52, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x69, 0x12, 0x1f, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xb2, 0xbb,
	0x18, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x50,
	0x0a, 0x18, 0x47, 0x72, 0x61, 0x66, 0x61, 0x6e, 0x61, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x62, 0x61,
	0x73, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x62, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x71, 0x0a, 0x19, 0x47, 0x72, 0x61, 0x66, 0x61, 0x6e, 0x61, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x75, 0x72, 0x69,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x55, 0x72, 0x69, 0x22, 0xd8, 0x01, 0x0a, 0x1a, 0x47, 0x72, 0x61, 0x66, 0x61, 0x6e, 0x61, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08,
	0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x49, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x4d,
	0x0a, 0x12, 0x47, 0x72, 0x61, 0x66, 0x61, 0x6e, 0x61, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x11, 0xba, 0xbb, 0x18,
	0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x9b, 0x01,
	0x0a, 0x13, 0x47, 0x72, 0x61, 0x66, 0x61, 0x6e, 0x61, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x75, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x75, 0x62, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x42, 0x35, 0x5a, 0x33, 0x66,
	0x72, 0x65, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x78, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x69, 0x6f,
	0x74, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x66, 0x72, 0x65, 0x65,
	0x7a, 0x6f, 0x6e, 0x65, 0x78, 0x5f, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x69, 0x6f, 0x74, 0x5f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_freezonex_openiiot_api_grafana_proto_rawDescOnce sync.Once
	file_freezonex_openiiot_api_grafana_proto_rawDescData = file_freezonex_openiiot_api_grafana_proto_rawDesc
)

func file_freezonex_openiiot_api_grafana_proto_rawDescGZIP() []byte {
	file_freezonex_openiiot_api_grafana_proto_rawDescOnce.Do(func() {
		file_freezonex_openiiot_api_grafana_proto_rawDescData = protoimpl.X.CompressGZIP(file_freezonex_openiiot_api_grafana_proto_rawDescData)
	})
	return file_freezonex_openiiot_api_grafana_proto_rawDescData
}

var file_freezonex_openiiot_api_grafana_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_freezonex_openiiot_api_grafana_proto_goTypes = []interface{}{
	(*GrafanaAuthorizeRequest)(nil),    // 0: freezonex.openiiot_api.GrafanaAuthorizeRequest
	(*GrafanaAuthorizeResponse)(nil),   // 1: freezonex.openiiot_api.GrafanaAuthorizeResponse
	(*GrafanaAccessTokenRequest)(nil),  // 2: freezonex.openiiot_api.GrafanaAccessTokenRequest
	(*GrafanaAccessTokenResponse)(nil), // 3: freezonex.openiiot_api.GrafanaAccessTokenResponse
	(*GrafanaUserRequest)(nil),         // 4: freezonex.openiiot_api.GrafanaUserRequest
	(*GrafanaUserResponse)(nil),        // 5: freezonex.openiiot_api.GrafanaUserResponse
	(*base_resp.BaseResponse)(nil),     // 6: base_resp.BaseResponse
}
var file_freezonex_openiiot_api_grafana_proto_depIdxs = []int32{
	6, // 0: freezonex.openiiot_api.GrafanaAuthorizeResponse.base_resp:type_name -> base_resp.BaseResponse
	6, // 1: freezonex.openiiot_api.GrafanaAccessTokenResponse.base_resp:type_name -> base_resp.BaseResponse
	6, // 2: freezonex.openiiot_api.GrafanaUserResponse.base_resp:type_name -> base_resp.BaseResponse
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_freezonex_openiiot_api_grafana_proto_init() }
func file_freezonex_openiiot_api_grafana_proto_init() {
	if File_freezonex_openiiot_api_grafana_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_freezonex_openiiot_api_grafana_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrafanaAuthorizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freezonex_openiiot_api_grafana_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrafanaAuthorizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freezonex_openiiot_api_grafana_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrafanaAccessTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freezonex_openiiot_api_grafana_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrafanaAccessTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freezonex_openiiot_api_grafana_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrafanaUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freezonex_openiiot_api_grafana_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrafanaUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_freezonex_openiiot_api_grafana_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_freezonex_openiiot_api_grafana_proto_goTypes,
		DependencyIndexes: file_freezonex_openiiot_api_grafana_proto_depIdxs,
		MessageInfos:      file_freezonex_openiiot_api_grafana_proto_msgTypes,
	}.Build()
	File_freezonex_openiiot_api_grafana_proto = out.File
	file_freezonex_openiiot_api_grafana_proto_rawDesc = nil
	file_freezonex_openiiot_api_grafana_proto_goTypes = nil
	file_freezonex_openiiot_api_grafana_proto_depIdxs = nil
}
