apiVersion: v3alpha1
service: 
  replicas: 1
  proxy: 
    paths: 
    - path: /web
      servicePort: 80
    - path: /nodered
      servicePort: 1880
    - path: /grafana
      servicePort: 3000
    - path: /tdengine
      servicePort: 6041
    - path: /emqx
      servicePort: 1883
  ports: 
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 1880
    targetPort: 1880
    protocol: TCP
    name: http
  - port: 43893
    targetPort: 43893
    protocol: UDP
    name: http
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  - port: 6041
    targetPort: 6041
    protocol: TCP
    name: http
  - port: 1883
    targetPort: 1883
    protocol: TCP
    name: http
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: http
  containers: 
  - name: nodered
    image: registry:5000/node-red:1.0.0
    volumeMounts: 
    - name: nodered_data
      mountPath: /data
    ports: 
    - containerPort: 1880
    - containerPort: 43893
    resources: 
      requests: 
        cpu: 10m
        memory: 128Mi
      limits: 
        cpu: 1000m
        memory: 4Gi
  - name: grafana
    image: registry:5000/grafana:1.0.0
    volumeMounts: 
    - name: grafana_data
      mountPath: /var/lib/grafana
    ports: 
    - containerPort: 3000
    resources: 
      requests: 
        cpu: 10m
        memory: 128Mi
      limits: 
        cpu: 1000m
        memory: 4Gi
  - name: tdengine
    image: registry:5000/tdengine:1.0.0
    volumeMounts: 
    - name: tdengine_data
      mountPath: /var/lib/taosw
    - name: tdengine_log
      mountPath: /var/log/taos
    ports: 
    - containerPort: 6030
    - containerPort: 6041
    #- containerPort: 6043-6049
    #- containerPort: 6043-6049/udp
    resources: 
      requests: 
        cpu: 10m
        memory: 128Mi
      limits: 
        cpu: 1000m
        memory: 4Gi
  - name: emqx
    image: registry:5000/emqx:5.1.3
    volumeMounts: 
    - name: emqx_data
      mountPath: /opt/emqx/data
    ports: 
    - containerPort: 1883
    - containerPort: 8083
    - containerPort: 8084
    - containerPort: 8883
    - containerPort: 18083
    resources: 
      requests: 
        cpu: 10m
        memory: 128Mi
      limits: 
        cpu: 1000m
        memory: 4Gi
  - name: web
    image: registry:5000/web:1.0.0
    ports: 
    - containerPort: 80
    resources: 
      requests: 
        cpu: 10m
        memory: 128Mi
      limits: 
        cpu: 1000m
        memory: 4Gi
  - name: mysql
    image: registry:5000/mysql:8.0.30
    volumeMounts: 
    - name: mysql_data
      mountPath: /var/lib/mysql
    ports: 
    - containerPort: 3306
    resources: 
      requests: 
        cpu: 10m
        memory: 128Mi
      limits: 
        cpu: 1000m
        memory: 4Gi