apiVersion: v3alpha1
service: 
  replicas: 1
  proxy: 
    paths: 
    - path: /server
      servicePort: 8085
    - path: /web
      servicePort: 80
    - path: /nodered
      servicePort: 1880
    - path: /grafana
      servicePort: 3000
    - path: /emqx
      servicePort: 18083
    - path: /tdengine
      servicePort: 6041
    - path: /mysql
      servicePort: 6033

  ports: 
  - port: 8085
    targetPort: 8085
    protocol: TCP
    name: server
  - port: 80
    targetPort: 80
    protocol: TCP
    name: web
  - port: 1880
    targetPort: 1880
    protocol: TCP
    name: nodered
  - port: 43893
    targetPort: 43893
    protocol: UDP
    name: noderedudp
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: grafana
  - port: 1883
    targetPort: 1883
    protocol: TCP
    name: emqx1
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: emqx2
  - port: 8084
    targetPort: 8084
    protocol: TCP
    name: emqx3
  - port: 8883
    targetPort: 8883
    protocol: TCP
    name: emqx4
  - port: 18083
    targetPort: 18083
    protocol: TCP
    name: emqx5
  - port: 6030
    targetPort: 6030
    protocol: TCP
    name: tdengine1
  - port: 6041
    targetPort: 6041
    protocol: TCP
    name: tdengine2
  - port: 6033
    targetPort: 3306
    protocol: TCP
    name: mysql

  containers: 
  - name: server
    image: eco-registry.supos.com/supvxcen/openiiot_server:1.0.0
    ports: 
    - containerPort: 8085
    resources: 
      requests: 
        cpu: 10m
        memory: 128Mi
      limits: 
        cpu: 1000m
        memory: 2Gi
  - name: web
    image: eco-registry.supos.com/supvxcen/openiiot_web:1.0.0
    ports: 
    - containerPort: 80
    resources: 
      requests: 
        cpu: 10m
        memory: 128Mi
      limits: 
        cpu: 1000m
        memory: 2Gi
  - name: nodered
    image: eco-registry.supos.com/supvxcen/openiiot_nodered:1.0.0
    ports: 
    - containerPort: 1880
    - containerPort: 43893
    resources: 
      requests: 
        cpu: 10m
        memory: 128Mi
      limits: 
        cpu: 1000m
        memory: 2Gi
  - name: grafana
    image: eco-registry.supos.com/supvxcen/openiiot_grafana_raw:1.0.0
    ports: 
    - containerPort: 3000
    resources: 
      requests: 
        cpu: 10m
        memory: 128Mi
      limits: 
        cpu: 1000m
        memory: 2Gi
  - name: emqx
    image: eco-registry.supos.com/supvxcen/openiiot_emqx:1.0.0
    ports: 
    - containerPort: 1883
    - containerPort: 8083
    - containerPort: 8084
    - containerPort: 8883
    - containerPort: 18083
    resources: 
      requests: 
        cpu: 10m
        memory: 128Mi
      limits: 
        cpu: 1000m
        memory: 2Gi

  - name: tdengine
    image: eco-registry.supos.com/supvxcen/openiiot_tdengine:1.0.0
    ports: 
    - containerPort: 6030
    - containerPort: 6041
    resources: 
      requests: 
        cpu: 10m
        memory: 128Mi
      limits: 
        cpu: 1000m
        memory: 2Gi

  - name: mysql
    image: eco-registry.supos.com/supvxcen/openiiot_mysql:1.0.0
    ports: 
    - containerPort: 3306
    resources: 
      requests: 
        cpu: 10m
        memory: 128Mi
      limits: 
        cpu: 1000m
        memory: 2Gi