{
 "title": "demo_air_quality_1",
 "time": { "from": "2023-09-18T23:48:32.769Z", "to": "2023-09-19T06:26:46.957Z" },
 "panels": [
  {
   "title": "Trend chart",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select * from demo.air_quality_1;"
    }
   ]
  },
  {
   "title": "Current status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last_row(ts, status) from demo.air_quality_1;"
    }
   ]
  },
  {
   "title": "Total running time ",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 7 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select status, sum(time_duration) /1000 as runtime from (select first(ts) as start_time, spread(ts) as time_duration, status from demo.air_quality_1 state_window(status)) where status <> \"running\" group by status;"
    }
   ]
  },
  {
   "title": "Machine Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select ts, status from demo.air_quality_1;"
    }
   ]
  },
  {
   "title": "Status list",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select ts, status from demo.air_quality_1 limit 10;"
    }
   ]
  }
 ]
}