// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model_openiiot

const TableNameFlowEdge = "flow_edge"

// FlowEdge mapped from table <flow_edge>
type FlowEdge struct {
	ID      int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FlowID  int64   `gorm:"column:flow_id;not null" json:"flow_id"`
	EdgeID  int64   `gorm:"column:edge_id;not null" json:"edge_id"`
	Script  *string `gorm:"column:script" json:"script"`
	Script2 *string `gorm:"column:script2" json:"script2"`
	Script3 *string `gorm:"column:script3" json:"script3"`
	Script4 *string `gorm:"column:script4" json:"script4"`
}

// TableName FlowEdge's table name
func (*FlowEdge) TableName() string {
	return TableNameFlowEdge
}
