// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model_openiiot

const TableNameFlowCore = "flow_core"

// FlowCore mapped from table <flow_core>
type FlowCore struct {
	ID      int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FlowID  int64   `gorm:"column:flow_id;not null" json:"flow_id"`
	CoreID  int64   `gorm:"column:core_id;not null" json:"core_id"`
	Script  *string `gorm:"column:script" json:"script"`
	Script2 *string `gorm:"column:script2" json:"script2"`
}

// TableName FlowCore's table name
func (*FlowCore) TableName() string {
	return TableNameFlowCore
}
