// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model_openiiot

const TableNameFlowApp = "flow_app"

// FlowApp mapped from table <flow_app>
type FlowApp struct {
	ID     int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FlowID int64   `gorm:"column:flow_id;not null" json:"flow_id"`
	AppID  int64   `gorm:"column:app_id;not null" json:"app_id"`
	Script *string `gorm:"column:script" json:"script"`
}

// TableName FlowApp's table name
func (*FlowApp) TableName() string {
	return TableNameFlowApp
}
