// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model_openiiot

const TableNameFlowEdge = "flow_edge"

// FlowEdge mapped from table <flow_edge>
type FlowEdge struct {
	ID     int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FlowID int64   `gorm:"column:flow_id;not null" json:"flow_id"`
	EdgeID int64   `gorm:"column:edge_id;not null" json:"edge_id"`
	Script *string `gorm:"column:script" json:"script"`
}

// TableName FlowEdge's table name
func (*FlowEdge) TableName() string {
	return TableNameFlowEdge
}
