// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model_openiiot

import (
	"time"
)

const TableNameGlobalConfig = "global_config"

// GlobalConfig mapped from table <global_config>
type GlobalConfig struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;not null;uniqueIndex:name,priority:1" json:"name"`
	Value      *string   `gorm:"column:value" json:"value"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName GlobalConfig's table name
func (*GlobalConfig) TableName() string {
	return TableNameGlobalConfig
}
