// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model_openiiot

import (
	"time"
)

const TableNameOpeniiotConfig = "openiiot_config"

// OpeniiotConfig mapped from table <openiiot_config>
type OpeniiotConfig struct {
	Pkey    int32     `gorm:"column:pkey;primaryKey;autoIncrement:true" json:"pkey"`
	Name    string    `gorm:"column:name;not null" json:"name"`
	Value   string    `gorm:"column:value;not null" json:"value"`
	AddDate time.Time `gorm:"column:add_date;not null;default:CURRENT_TIMESTAMP" json:"add_date"`
}

// TableName OpeniiotConfig's table name
func (*OpeniiotConfig) TableName() string {
	return TableNameOpeniiotConfig
}
