// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model_openiiot

import (
	"time"
)

const TableNameTenant = "tenant"

// Tenant mapped from table <tenant>
type Tenant struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;not null;uniqueIndex:name,priority:1" json:"name"`
	Description *string   `gorm:"column:description" json:"description"`
	IsDefault   *bool     `gorm:"column:is_default" json:"is_default"`
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName Tenant's table name
func (*Tenant) TableName() string {
	return TableNameTenant
}
