// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model_openiiot

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID              int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username        string     `gorm:"column:username;not null;uniqueIndex:username,priority:1" json:"username"`
	Password        *string    `gorm:"column:password" json:"password"`
	Description     *string    `gorm:"column:description" json:"description"`
	TenantID        int64      `gorm:"column:tenant_id;not null" json:"tenant_id"`
	Role            string     `gorm:"column:role;not null" json:"role"`
	AuthID          *string    `gorm:"column:auth_id" json:"auth_id"`
	Source          *string    `gorm:"column:source" json:"source"`
	Token           *string    `gorm:"column:token" json:"token"`
	TokenUpdatetime *time.Time `gorm:"column:token_updatetime;default:CURRENT_TIMESTAMP" json:"token_updatetime"`
	UpdateTime      time.Time  `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	CreateTime      time.Time  `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
