// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model_openiiot

import (
	"time"
)

const TableNameWmsWarehouse = "wms_warehouse"

// WmsWarehouse mapped from table <wms_warehouse>
type WmsWarehouse struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         string    `gorm:"column:name;not null;uniqueIndex:name,priority:1" json:"name"`
	WarehouseID  string    `gorm:"column:warehouse_id;not null;uniqueIndex:warehouse_id,priority:1" json:"warehouse_id"`
	Type         string    `gorm:"column:type;not null" json:"type"`
	Manager      *string   `gorm:"column:manager" json:"manager"`
	Department   *string   `gorm:"column:department" json:"department"`
	Email        *string   `gorm:"column:email" json:"email"`
	ProjectGroup *string   `gorm:"column:project_group" json:"project_group"`
	Note         *string   `gorm:"column:note" json:"note"`
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName WmsWarehouse's table name
func (*WmsWarehouse) TableName() string {
	return TableNameWmsWarehouse
}
