// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model_openiiot

import (
	"time"
)

const TableNameWmsStorageLocation = "wms_storage_location"

// WmsStorageLocation mapped from table <wms_storage_location>
type WmsStorageLocation struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	WarehouseID int64     `gorm:"column:warehouse_id;not null" json:"warehouse_id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Occupied    *bool     `gorm:"column:occupied" json:"occupied"`
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName WmsStorageLocation's table name
func (*WmsStorageLocation) TableName() string {
	return TableNameWmsStorageLocation
}
