// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model_openiiot

import (
	"time"
)

const TableNameWmsInboundRecord = "wms_inbound_record"

// WmsInboundRecord mapped from table <wms_inbound_record>
type WmsInboundRecord struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	InboundID  int64     `gorm:"column:inbound_id;not null" json:"inbound_id"`
	Rfid       *string   `gorm:"column:rfid" json:"rfid"`
	MaterialID int64     `gorm:"column:material_id;not null" json:"material_id"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName WmsInboundRecord's table name
func (*WmsInboundRecord) TableName() string {
	return TableNameWmsInboundRecord
}
