// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model_openiiot

import (
	"time"
)

const TableNameWmsOutbound = "wms_outbound"

// WmsOutbound mapped from table <wms_outbound>
type WmsOutbound struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RefID      string    `gorm:"column:ref_id;not null;uniqueIndex:ref_id,priority:1" json:"ref_id"`
	Type       string    `gorm:"column:type;not null" json:"type"`
	Source     string    `gorm:"column:source;not null" json:"source"`
	Note       *string   `gorm:"column:note" json:"note"`
	Operator   string    `gorm:"column:operator;not null" json:"operator"`
	Status     *string   `gorm:"column:status" json:"status"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName WmsOutbound's table name
func (*WmsOutbound) TableName() string {
	return TableNameWmsOutbound
}
